export { default as EducationSection } from "./education"
export { default as SkillsSection } from "./skills"
export { default as WorkExperienceSection } from "./work-experience"
export { default as VolunteeringSection } from "./volunteering"
export { default as ProjectsSection } from "./projects"
export { default as HeroBanner } from "./hero-banner"
